// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using teamProject.Models;

#nullable disable

namespace teamProject.Migrations
{
    [DbContext(typeof(TeamContext))]
    partial class TeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("teamProject.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.BranchMobile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Br_Id")
                        .HasColumnType("int");

                    b.Property<string>("Br_Mob1")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Br_Mob2")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Br_Id")
                        .IsUnique();

                    b.ToTable("BrancheMoblies", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.BranchPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Br_Id")
                        .HasColumnType("int");

                    b.Property<string>("Br_Ph1")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Br_Ph2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Br_Id")
                        .IsUnique();

                    b.ToTable("BranchePhones", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.Central", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Gov_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Gov_Id");

                    b.ToTable("Centrals", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Central_Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Offer_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Package_Id")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Service_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Central_Id");

                    b.HasIndex("Offer_Id");

                    b.HasIndex("Package_Id");

                    b.HasIndex("Service_Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.Governerate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Branch_Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Branch_Id");

                    b.ToTable("Governerates", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Servuce_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Servuce_Id");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.Provider_Package", b =>
                {
                    b.Property<int>("Package_Id")
                        .HasColumnType("int");

                    b.Property<int>("provider_Id")
                        .HasColumnType("int");

                    b.HasKey("Package_Id", "provider_Id");

                    b.HasIndex("provider_Id");

                    b.ToTable("Provider_Package", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.myServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("teamProject.Models.BranchMobile", b =>
                {
                    b.HasOne("teamProject.Models.Branch", "branch")
                        .WithOne("BranchMobiles")
                        .HasForeignKey("teamProject.Models.BranchMobile", "Br_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("teamProject.Models.BranchPhone", b =>
                {
                    b.HasOne("teamProject.Models.Branch", "branch")
                        .WithOne("BranchPhones")
                        .HasForeignKey("teamProject.Models.BranchPhone", "Br_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("teamProject.Models.Central", b =>
                {
                    b.HasOne("teamProject.Models.Governerate", "Governerate")
                        .WithMany("centrals")
                        .HasForeignKey("Gov_Id");

                    b.Navigation("Governerate");
                });

            modelBuilder.Entity("teamProject.Models.Client", b =>
                {
                    b.HasOne("teamProject.Models.Central", "Central")
                        .WithMany()
                        .HasForeignKey("Central_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teamProject.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("Offer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teamProject.Models.package", "package")
                        .WithMany()
                        .HasForeignKey("Package_Id");

                    b.HasOne("teamProject.Models.myServiceProvider", "ServiceProvider")
                        .WithMany("Clients")
                        .HasForeignKey("Service_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Central");

                    b.Navigation("Offer");

                    b.Navigation("ServiceProvider");

                    b.Navigation("package");
                });

            modelBuilder.Entity("teamProject.Models.Governerate", b =>
                {
                    b.HasOne("teamProject.Models.Branch", "Branch")
                        .WithMany("Governerates")
                        .HasForeignKey("Branch_Id");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("teamProject.Models.Offer", b =>
                {
                    b.HasOne("teamProject.Models.myServiceProvider", "ServiceProvider")
                        .WithMany("Offers")
                        .HasForeignKey("Servuce_Id");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("teamProject.Models.Provider_Package", b =>
                {
                    b.HasOne("teamProject.Models.package", "Package")
                        .WithMany("Provider_Packages")
                        .HasForeignKey("Package_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teamProject.Models.myServiceProvider", "ServiceProvider")
                        .WithMany("Provider_Packages")
                        .HasForeignKey("provider_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("teamProject.Models.Branch", b =>
                {
                    b.Navigation("BranchMobiles");

                    b.Navigation("BranchPhones");

                    b.Navigation("Governerates");
                });

            modelBuilder.Entity("teamProject.Models.Governerate", b =>
                {
                    b.Navigation("centrals");
                });

            modelBuilder.Entity("teamProject.Models.myServiceProvider", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Offers");

                    b.Navigation("Provider_Packages");
                });

            modelBuilder.Entity("teamProject.Models.package", b =>
                {
                    b.Navigation("Provider_Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
